global:
scrape_interval: 15s
evaluation_interval: 15s
scrape_configs:

job_name: 'controller'
static_configs:

targets: ['controller:8080']
metrics_path: '/actuator/prometheus'


job_name: 'prometheus'
static_configs:

targets: ['localhost:9090']



